--- 
spring: 
  datasource: 
    password: pracownia
    url: jdbc:postgresql://localhost:5432/organizer 
    username: pracownia
  jpa: 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate: 
      ddl-auto: create-drop